[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Redirect confirmation emails to custom handler
[[redirects]]
  from = "/*"
  to = "/confirm.html"
  status = 200
  conditions = {Query = {confirmation_token = ":token"}}

[[redirects]]
  from = "/*"
  to = "/confirm.html"
  status = 200
  conditions = {Query = {recovery_token = ":token"}}

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 